### ISSUE TITLE
Cannot import the Library

### ISSUE THREAD

**Issue by sylum** [gusgonnet/particle-fsm#3]
Hi guys,

Your FSM library look promising that why I wanna give a try.
Currently I'm facing an import error when trying to import the file "particle-fsm-master.zip"
Below the error :
Invalid library found in C:\Users\cedri\Documents\Arduino\libraries\particle-fsm-master : Missing 'maintainer' from library.

So I have tried to fix the library.properties file but even after that I still not able to compile the sample exemple.

Any idea about the issue,
Thx in advance,
Cedric

**Comment by gusgonnet** [comment]
Hi Cedric, this FSM library is pretty amazing. I can say that because I did not code it myself but rather just ported it to particle.

One question: are you importing this library in an arduino project or in a Particle project?
Are you using the Particle workbench? if so, why not add it to your project by the menu => CTRL SHIFT P => Particle: install library

you can find the particle workbench here:
https://www.particle.io/workbench/
Cheers,
Gustavo.

**Comment by sylum** [comment]
Hi Gustavo,

Thx for your answer. Your right, i'm made a mistake cause a tring using the
particle-fsm library on the arduino project (which made for particle).

Lesson learn, so  right now i'm jumping on  this library for manipulation
FSM on arduino
https://github.com/jonblack/arduino-fsm

Cheers,

Cedric
